#!/usr/bin/env node
/* ==========================================================================
   Babyz Pizza — local writer server
   --------------------------------------------------------------------------
   Zero dependencies. Run it on the machine where you want to record orders.

       node server.js            (or double-click start-local.bat)

   Then open  http://localhost:8787

   THREE data files are managed here:

     1. MAIN   <Desktop>\Babyz Pizza Data\babyz-data.js
               the main local file — the real copy

     2. STAGE  <Desktop>\Babyz Pizza Data\babyz-data-pending.js
               the 2nd local copy — deletions land here first, so MAIN is
               never touched until you press "Confirm delete" in the app

     3. REPO   <repo>\data\babyz-data.js
               the copy the website always READS from, and the one you
               commit & push so the hosted site shows the new data

   Rules:
     • adding a row      -> written to MAIN + STAGE + REPO
     • deleting a row    -> written to STAGE only
     • undo deletes      -> STAGE is rebuilt from MAIN
     • confirm delete    -> STAGE is pushed into MAIN + REPO
   ========================================================================== */
'use strict';

const http = require('http');
const fs = require('fs');
const path = require('path');
const os = require('os');

const PORT = Number(process.env.BABYZ_PORT || 8787);
const HOST = '127.0.0.1';
const ROOT = __dirname;

const MAIN_NAME = 'babyz-data.js';
const STAGE_NAME = 'babyz-data-pending.js';

const DESKTOP_DIR = process.env.BABYZ_DESKTOP_DIR || path.join(os.homedir(), 'Desktop', 'Babyz Pizza Data');
const FALLBACK_DIR = path.join(ROOT, 'local-data');

const REPO_FILE = path.join(ROOT, 'data', MAIN_NAME);

let activeDir = DESKTOP_DIR;
let MAIN_FILE = path.join(DESKTOP_DIR, MAIN_NAME);
let STAGE_FILE = path.join(DESKTOP_DIR, STAGE_NAME);

function ensureDir(dir) {
  try { fs.mkdirSync(dir, { recursive: true }); return true; }
  catch (e) { return false; }
}

function resolvePaths() {
  activeDir = ensureDir(DESKTOP_DIR) ? DESKTOP_DIR : (ensureDir(FALLBACK_DIR), FALLBACK_DIR);
  MAIN_FILE = path.join(activeDir, MAIN_NAME);
  STAGE_FILE = path.join(activeDir, STAGE_NAME);
}

/* ---------------------------------------------------------------- file io */
const HEADER_MAIN =
  '/* Babyz Pizza - revenue & order data snapshot (MAIN local copy).\n' +
  '   Generated by the Babyz Revenue app. Safe to commit to Git.\n' +
  '   Edit rows in the app (local mode) - this file is rewritten automatically. */';

const HEADER_STAGE =
  '/* Babyz Pizza - 2nd local copy (STAGING).\n' +
  '   Deletions are applied here FIRST. The main local file and the repo copy\n' +
  '   are only changed when you press "Confirm delete" in the app. */';

function serialize(data, header) {
  return header + '\nwindow.BABYZ_DATA = ' + JSON.stringify(data, null, 2) + ';\n';
}

function writeAtomic(file, text) {
  ensureDir(path.dirname(file));
  const tmp = file + '.tmp';
  fs.writeFileSync(tmp, text, 'utf8');
  fs.renameSync(tmp, file);
}

function readData(file) {
  try {
    if (!fs.existsSync(file)) return null;
    const txt = fs.readFileSync(file, 'utf8');
    const i = txt.indexOf('{'), j = txt.lastIndexOf('}');
    if (i < 0 || j < 0) return null;
    return JSON.parse(txt.slice(i, j + 1));
  } catch (e) { return null; }
}

function stripPending(data) {
  if (!data) return data;
  const copy = JSON.parse(JSON.stringify(data));
  if (copy.meta) delete copy.meta.pendingDeletes;
  return copy;
}

/* The add/edit path takes the full base (which still holds rows that are only
   staged for deletion) and the view (base minus those rows). Writing the view
   straight over STAGE would silently finish those deletions: /api/confirm reads
   STAGE and pushes it into MAIN and REPO, and by then the rows are already gone
   from it. So rebuild STAGE as base + the staged rows removed again, keeping the
   deletions removable through /api/undo. */
function mergeView(base, view) {
  const out = JSON.parse(JSON.stringify(base || {}));
  if (!view || typeof view !== 'object') return out;
  for (const k of ['offlineOrders', 'swiggyOrders', 'swiggyPayouts', 'investments']) {
    if (!Array.isArray(view[k]) || !Array.isArray(out[k])) continue;
    const seen = {};
    view[k].forEach((r) => { if (r && r.id != null) seen[r.id] = true; });
    out[k] = out[k].filter((r) => (r && r.id != null) ? seen[r.id] : true);
  }
  return out;
}

function validate(data) {
  if (!data || typeof data !== 'object') return 'payload is not an object';
  for (const k of ['offlineOrders', 'swiggyOrders', 'swiggyPayouts', 'investments']) {
    if (!Array.isArray(data[k])) return 'missing array: ' + k;
  }
  if (!data.menus || typeof data.menus !== 'object') return 'missing menus';
  return null;
}

function touch(data) {
  data.meta = data.meta || {};
  data.meta.updatedAt = new Date().toISOString();
  return data;
}

function writeMain(data) { writeAtomic(MAIN_FILE, serialize(data, HEADER_MAIN)); }
function writeStage(view, pending) {
  const payload = touch(JSON.parse(JSON.stringify(view || {})));
  payload.meta.pendingDeletes = Array.isArray(pending) ? pending : [];
  writeAtomic(STAGE_FILE, serialize(payload, HEADER_STAGE));
}
function writeRepo(data) { writeAtomic(REPO_FILE, serialize(data, HEADER_MAIN)); }

function fileInfo() {
  return {
    main: MAIN_FILE,
    stage: STAGE_FILE,
    repo: REPO_FILE,
    dir: activeDir,
    exists: {
      main: fs.existsSync(MAIN_FILE),
      stage: fs.existsSync(STAGE_FILE),
      repo: fs.existsSync(REPO_FILE)
    }
  };
}

/* ---------------------------------------------------------------- static */
const MIME = {
  '.html': 'text/html; charset=utf-8', '.htm': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8', '.mjs': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8', '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml', '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg',
  '.gif': 'image/gif', '.webp': 'image/webp', '.ico': 'image/x-icon',
  '.woff': 'font/woff', '.woff2': 'font/woff2', '.txt': 'text/plain; charset=utf-8',
  '.md': 'text/markdown; charset=utf-8'
};

function serveStatic(req, res, urlPath) {
  let rel = decodeURIComponent(urlPath.split('?')[0]);
  if (rel === '/' || rel === '') rel = '/index.html';
  const full = path.normalize(path.join(ROOT, rel));
  if (!full.startsWith(ROOT)) { res.writeHead(403); res.end('Forbidden'); return; }

  fs.stat(full, (err, st) => {
    if (err || !st.isFile()) {
      res.writeHead(404, { 'Content-Type': 'text/plain; charset=utf-8' });
      res.end('404 Not found: ' + rel);
      return;
    }
    res.writeHead(200, {
      'Content-Type': MIME[path.extname(full).toLowerCase()] || 'application/octet-stream',
      'Cache-Control': 'no-store, must-revalidate',
      'Access-Control-Allow-Origin': '*'
    });
    fs.createReadStream(full).pipe(res);
  });
}

/* ---------------------------------------------------------------- helpers */
/* Only these origins may talk to the writer:
     - "null"        a page opened straight off disk (file://)
     - localhost     the local page itself
   Any other origin (a website the user happens to have open) gets NO CORS
   headers, so its preflight fails and it cannot reach the data files. */
const LOCAL_ORIGIN = /^https?:\/\/(localhost|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|\[::1\])(:\d+)?$/i;

function originAllowed(req) {
  const origin = req.headers.origin;
  if (!origin || origin === 'null') return true;
  return LOCAL_ORIGIN.test(origin);
}

function cors(req, res) {
  if (!originAllowed(req)) return false;
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.setHeader('Access-Control-Max-Age', '86400');
  return true;
}
function json(res, code, obj) {
  res.writeHead(code, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' });
  res.end(JSON.stringify(obj));
}
function readBody(req) {
  return new Promise((resolve, reject) => {
    let raw = '';
    req.on('data', c => {
      raw += c;
      if (raw.length > 16 * 1024 * 1024) { reject(new Error('payload too large')); req.destroy(); }
    });
    req.on('end', () => resolve(raw || '{}'));
    req.on('error', reject);
  });
}

/* ---------------------------------------------------------------- server */
const server = http.createServer(async (req, res) => {
  const url = req.url || '/';

  if (req.method === 'OPTIONS') {
    if (!cors(req, res)) { res.writeHead(403); res.end(); return; }
    res.writeHead(204); res.end(); return;
  }

  if (!url.startsWith('/api/')) { serveStatic(req, res, url); return; }

  /* a cross-origin page that is not local gets nothing from the API */
  if (!cors(req, res)) {
    res.writeHead(403, { 'Content-Type': 'application/json; charset=utf-8' });
    res.end(JSON.stringify({ ok: false, error: 'cross-origin requests are not allowed' }));
    return;
  }
  const route = url.split('?')[0];
  const method = req.method;

  try {
    /* -------- health -------- */
    if (route === '/api/health' && method === 'GET') {
      json(res, 200, Object.assign({ ok: true, app: 'babyz-revenue', port: PORT }, fileInfo(), {
        desktopFile: MAIN_FILE, stageFile: STAGE_FILE, repoFile: REPO_FILE
      }));
      return;
    }

    /* -------- state: always read the REPO copy, plus staged deletions -------- */
    if (route === '/api/state' && method === 'GET') {
      const base = readData(REPO_FILE) || readData(MAIN_FILE) || readData(STAGE_FILE);
      const stage = readData(STAGE_FILE);
      const pending = (stage && stage.meta && Array.isArray(stage.meta.pendingDeletes))
        ? stage.meta.pendingDeletes : [];
      json(res, 200, {
        ok: true,
        base: base ? stripPending(base) : null,
        pending: pending,
        files: fileInfo(),
        readFrom: REPO_FILE
      });
      return;
    }

    /* -------- add a row: MAIN + STAGE + REPO -------- */
    if (route === '/api/rows' && method === 'POST') {
      const body = JSON.parse(await readBody(req));
      const data = body.data;
      const bad = validate(data);
      if (bad) { json(res, 400, { ok: false, error: bad }); return; }

      touch(data);
      writeMain(data);
      writeRepo(data);
      writeStage(mergeView(data, body.view), body.pending || []);

      console.log('[add]     MAIN + STAGE + REPO written');
      json(res, 200, { ok: true, action: 'add', files: fileInfo() });
      return;
    }

    /* -------- stage a deletion: STAGE only -------- */
    if (route === '/api/stage' && method === 'POST') {
      const body = JSON.parse(await readBody(req));
      const bad = validate(body.view);
      if (bad) { json(res, 400, { ok: false, error: bad }); return; }

      writeStage(body.view, body.pending || []);
      console.log('[stage]   STAGE only \u2014 ' + (body.pending || []).length + ' pending deletion(s)');
      json(res, 200, {
        ok: true, action: 'stage', pending: (body.pending || []).length,
        files: fileInfo()
      });
      return;
    }

    /* -------- undo: rebuild STAGE from MAIN -------- */
    if (route === '/api/undo' && method === 'POST') {
      const main = readData(MAIN_FILE);
      if (!main) { json(res, 404, { ok: false, error: 'main local file not found' }); return; }

      const base = stripPending(main);
      writeStage(base, []);
      console.log('[undo]    STAGE rebuilt from MAIN');
      json(res, 200, { ok: true, action: 'undo', base: base, files: fileInfo() });
      return;
    }

    /* -------- confirm: push STAGE into MAIN + REPO -------- */
    if (route === '/api/confirm' && method === 'POST') {
      const stage = readData(STAGE_FILE);
      if (!stage) { json(res, 404, { ok: false, error: 'staged copy not found' }); return; }

      const pending = (stage.meta && Array.isArray(stage.meta.pendingDeletes)) ? stage.meta.pendingDeletes : [];
      const data = touch(stripPending(stage));
      writeMain(data);
      writeRepo(data);
      writeStage(data, []);

      console.log('[confirm] ' + pending.length + ' deletion(s) pushed STAGE -> MAIN + REPO');
      json(res, 200, {
        ok: true, action: 'confirm', applied: pending.length,
        base: data, files: fileInfo()
      });
      return;
    }

    json(res, 404, { ok: false, error: 'unknown endpoint' });
  } catch (e) {
    json(res, 500, { ok: false, error: e.message });
  }
});

resolvePaths();

server.listen(PORT, HOST, () => {
  const line = '='.repeat(70);
  console.log('\n' + line);
  console.log('  \uD83C\uDF55  Babyz Pizza - Revenue & Order Tracker (local writer)');
  console.log(line);
  console.log('  Open in your browser :  http://localhost:' + PORT);
  console.log('  MAIN  local file     :  ' + MAIN_FILE);
  console.log('  STAGE 2nd local copy :  ' + STAGE_FILE);
  console.log('  REPO  copy (commit)  :  ' + REPO_FILE);
  console.log(line);
  console.log('  Add a row      -> MAIN + STAGE + REPO');
  console.log('  Delete a row   -> STAGE only (main file untouched)');
  console.log('  Undo deletes   -> STAGE rebuilt from MAIN');
  console.log('  Confirm delete -> STAGE pushed into MAIN + REPO');
  console.log('  Press Ctrl+C to stop.\n');
});

server.on('error', (e) => {
  if (e.code === 'EADDRINUSE') {
    console.error('\nPort ' + PORT + ' is already in use.');
    console.error('Either the server is already running (just open http://localhost:' + PORT + ')');
    console.error('or start it on another port:  set BABYZ_PORT=8788 && node server.js\n');
  } else {
    console.error(e);
  }
  process.exit(1);
});
